# Generated by Django 3.1.7 on 2021-03-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.CharField(max_length=10, null=True, verbose_name='Price'),
        ),
    ]
