# Generated by Django 3.1.7 on 2021-04-02 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_item_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='subCategory',
            new_name='sub_category',
        ),
    ]
