# Generated by Django 3.1.7 on 2022-01-10 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210401_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
