# Generated by Django 3.1.7 on 2022-01-11 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220111_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Review',
            new_name='review',
        ),
    ]
