# Generated by Django 3.1.7 on 2022-01-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220112_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=2000, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=2000, verbose_name='Sobrenome')),
                ('data_nasc', models.DateField(verbose_name='Data de Nascimento')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
