# Generated by Django 4.0.1 on 2022-01-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_usuario_avatar_alter_usuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=models.FileField(default='', upload_to='uploads/'),
        ),
    ]
