# Generated by Django 4.0.1 on 2022-01-14 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_usuario_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='avatar',
            new_name='file',
        ),
    ]
