# Generated by Django 3.1.7 on 2021-03-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='postalCode',
            field=models.CharField(max_length=9, null=True, verbose_name='Postal Code'),
        ),
    ]
