# Generated by Django 3.1.7 on 2021-03-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210322_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='typeUser',
            field=models.CharField(choices=[('E', 'Employee'), ('C', 'Client')], max_length=9, null='C', verbose_name='Type User'),
            preserve_default='C',
        ),
    ]
