# Generated by Django 3.1.7 on 2021-03-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210323_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='typeUser',
            field=models.CharField(choices=[('E', 'Employee'), ('C', 'Client'), ('D', 'DEV'), ('A', 'Admin')], default='C', max_length=9, verbose_name='Type User'),
        ),
    ]
