# Generated by Django 3.1.7 on 2021-04-02 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210324_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='typeUser',
            new_name='type_user',
        ),
    ]
